# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Mike Holownych
  admin_email: mike.holownych@gmail.com
  admin_password: jack@345
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: mholownych-blocipedia.heroku.com
  secret_key_base: 5c05e067c61f1c05abe620010eb6ccc878e661ea0d022ef974307b53133b8a7308747eea018e567ad87e8f775672dc5d02b3fe70ba1b88c055c022c14dc4a076

test:
  domain_name: mholownych-blocipedia.heroku.com 
  secret_key_base: 3af6d13b78861cc5b30d7a9b63c40fd8f70d5866b16eb8d22a80ea6d162e957dd54d81aa66342653e511ed304cbb3da470fc8f400027bc8ebbd97f2d82cb90df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
